UPDATE STUDENTS
SET NAME = NULL
WHERE 
  CASE
    WHEN MARKS >= 0 AND MARKS <= 9 THEN 1
    WHEN MARKS >= 10 AND MARKS <= 19 THEN 2
    WHEN MARKS >= 20 AND MARKS <= 29 THEN 3
    WHEN MARKS >= 30 AND MARKS <= 39 THEN 4
    WHEN MARKS >= 40 AND MARKS <= 49 THEN 5
    WHEN MARKS >= 50 AND MARKS <= 59 THEN 6
    WHEN MARKS >= 60 AND MARKS <= 69 THEN 7
    WHEN MARKS >= 70 AND MARKS <= 79 THEN 8
    WHEN MARKS >= 80 AND MARKS <= 89 THEN 9
    ELSE 10
  END < 8;
  
SELECT NAME,
    CASE 
        WHEN MARKS >= 0 AND MARKS <= 9 THEN 1
        WHEN MARKS >= 10 AND MARKS <= 19 THEN 2
        WHEN MARKS >= 20 AND MARKS <= 29 THEN 3
        WHEN MARKS >= 30 AND MARKS<= 39 THEN 4
        WHEN MARKS >= 40 AND MARKS <= 49 THEN 5
        WHEN MARKS >= 50 AND MARKS <= 59 THEN 6
        WHEN MARKS >= 60 AND MARKS <= 69 THEN 7
        WHEN MARKS >= 70 AND MARKS <= 79 THEN 8
        WHEN MARKS >= 80 AND MARKS <= 89 THEN 9
        ELSE 10
END AS GRADE, 
MARKS
FROM STUDENTS
ORDER BY 
    CASE 
        WHEN MARKS > 8 THEN GRADE ELSE GRADE 
    END DESC, 
NAME ASC;