SELECT SUBM.HACKER_ID  , HAC.NAME 
FROM CHALLENGES AS CHAL

LEFT JOIN DIFFICULTY AS DIFF 
    ON CHAL.DIFFICULTY_LEVEL = DIFF.DIFFICULTY_LEVEL
INNER JOIN SUBMISSIONS AS SUBM 
    ON SUBM.CHALLENGE_ID = CHAL.CHALLENGE_ID
RIGHT JOIN HACKERS AS HAC 
    ON SUBM.HACKER_ID = HAC.HACKER_ID
    
WHERE DIFF.SCORE = SUBM.SCORE
GROUP BY HAC.NAME, SUBM.HACKER_ID
HAVING COUNT(HAC.NAME) > 1 
    -- เลือกแสดงแค่ จำนวนชื่อที่ซ้ำมากกว่า 1
ORDER BY COUNT(HAC.NAME) DESC, SUBM.HACKER_ID ASC;